[package]
name = "aalto_tg_bot"
version = "0.1.0"
authors = ["Sild <sildtm@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telebot = "0.3.1"
futures = "0.1"